[project]
name = "dspy-testing"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.4.1",
    "dspy>=3.0.3",
    "dspy-ai>=3.0.3",
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "jupyter>=1.1.1",
]
